In [7]:
numbers = [1,2,3,4,5]

In [9]:
squares = [x ** 3 for x in numbers]  #  1*1*1  number lai squares ma rakeko 3 sanga ...2*2*2  3*3*3
print(squares)


[1, 8, 27, 64, 125]


In [15]:
marks =[50,60,70,80,90]
passedmark=[i for i in marks if i >=60]  #passed marks nikalda   i ko tau ma chai je rakda ni hunxa

print(passedmark)

[60, 70, 80, 90]


In [16]:
#list sakeo aba function

In [17]:
def cacuate_average(marks):
    return sum(marks)/len(marks)

In [24]:
marks =[60,70,80,90]
print(cacuate_average(marks))

75.0


In [38]:
def check_result(name, marks):  #student harule afno marks halera pass vayo ki nai vanera chack garna
    if marks >=60:
     return name +" pass"
    else:
        return name + " fail"

In [39]:
print(check_result("Sachin",90))


Sachin pass


In [40]:
print( check_result("sita",59))

sita fail


In [41]:
#Data Cleaning

In [61]:
data= [10, 20, None, 40, None, 60 , 50]  #none haru hataune

In [62]:
clear_data= [value for value in data if value is not None]  #value vako tauma je lekeni hunxa
print(clear_data)

[10, 20, 40, 60, 50]


In [63]:
 names=["Sachin","ram","sita","hari","Sachin","sita","ram","ram","Sachin","ram","sita","hari","Sachin","sita","ram","ram"]

In [60]:

unique_names = list(set(names))  #dabal vako name number harulai 1 ota matra dekauxa jati ota same vaeni yauta matra print garxa
print(unique_names)

['sita', 'ram', 'hari', 'Sachin']


In [71]:
try:
    age =int(input("Enter your age"))
    print("your age is", age)  #number 22 halda your age is 22 vanxa
except ValueError:#yadi age na halera " # yasto haleo vani talako print hunxa
    print("please enter your valide age")

Enter your age 45


your age is 45


In [72]:
 #importing Libraris

In [75]:
import math
print(math.sqrt(25))
print(math.pi)

5.0
3.141592653589793


In [76]:
 #FIRST INTRODUCTION TO NUMPY.
#MACHINE LEARNING USES ALOT OF NUMERAICAL DATA.NUMPAY GIVES US EFFICIENT NUMERICAL ARRAYS.

In [80]:
import numpy as np  #numpy lai np garako

In [82]:
numbers = np.array([10,20,30,40,50])
print(numbers)

[10 20 30 40 50]


In [84]:
print("mean", numbers.mean())  # average nikalda
print("max",numbers.max())  # bicha ko nikalda
print("min",numbers.min())  #sabai vanda sano nikalda

mean 30.0
max 50
min 10


In [85]:
print(numbers+10)

[20 30 40 50 60]


In [86]:
print(numbers*2)


[ 20  40  60  80 100]


In [89]:
print(numbers ** 2)

[ 100  400  900 1600 2500]


In [96]:
students= [
    {"name":"ram","marks":90},
    {"name":"hari","marks":99},
    {"name":"sita","marks":68},
    {"name":"gita","marks":45},
]
marks =[student["marks"] for student in students]
print("Total student:",len(students))
print ("Heighst marks:",max(marks))
print ("lowest marks:",min(marks))
print ("Average mark:",sum(marks)/len(marks))
print("Results:")

for student in students:
    if student["marks"]>= 60:
        print(student["name"]," pass")
    else:
        print(student["name"]," fail")

Total student: 4
Heighst marks: 99
lowest marks: 45
Average mark: 75.5
Results:
ram  pass
hari  pass
sita  pass
gita  fail


In [118]:
students= [
    {"name":"ram","marks":90},
    {"name":"hari","marks":99},
    {"name":"sita","marks":68},
    {"name":"gita","marks":59},
    {"name":"alina","marks":45}
]
passed = 0
failed = 0
for student in students:
    if student["marks"]>= 60:
        passed += 1
    else:
        failed += 1
topstudent = max (students, key=lambda s: s["marks"])
passpercantage = passed/len(students)*100
print("passed: " , passed)
print("failed: " , failed)
print("top student : ", topstudent["name"])
print ("pass percantage:",passpercantage)
        
#for student in students:
    #print(student["name"],student["grade"],student["marks"])

passed:  3
failed:  2
top student :  hari
pass percantage: 60.0
