In [1]:
import numpy as np
a = np.array([1,2,3,4,5,6])
print (a.reshape(2,-1))
 


[[1 2 3]
 [4 5 6]]


In [14]:
a =np.array([1,2,3,45,])
print("add:",a+10)

add: [11 12 13 55]


In [22]:
a =np.array([1,2,3,5,])
print("sub:",a-5)

sub: [-4 -3 -2  0]


In [24]:
a =np.array([1,2,3,5,])
print("mul:",a*10)

mul: [10 20 30 50]


In [27]:
a =np.array([1,2,3,5,])
print("div:",a/5)

div: [0.2 0.4 0.6 1. ]


In [30]:
a = np.array([1,2,3,4,5])
b= np.array([6,7,8,9,10])
print("add:",a+b)
print("sub:",a-b)
print("mul:",a*b)
print("div:",a/b)
print("power:",a**b)


add: [ 7  9 11 13 15]
sub: [-5 -5 -5 -5 -5]
mul: [ 6 14 24 36 50]
div: [0.16666667 0.28571429 0.375      0.44444444 0.5       ]
power: [      1     128    6561  262144 9765625]


In [31]:
#Universal Function

In [32]:
a = np.array([1,4,9,16])
print("aquare root:",np.sqrt(a))
print("log:",np.log(a))
print("exp:",np.sin(a))
print("sin:",np.sin(a))
print("cos:",np.sin(a))

aquare root: [1. 2. 3. 4.]
log: [0.         1.38629436 2.19722458 2.77258872]
exp: [ 0.84147098 -0.7568025   0.41211849 -0.28790332]
sin: [ 0.84147098 -0.7568025   0.41211849 -0.28790332]
cos: [ 0.84147098 -0.7568025   0.41211849 -0.28790332]


In [35]:
data = np.array([
    [10,20,30],
    [40,50,60],
    [70,80,90]
])
print("mean of all values:")
print(data.mean())

print("\nMean of each column:")
print(data.mean(axis=0))

print("\nMean of each row:")
print(data.mean(axis=1))

mean of all values:
50.0

Mean of each column:
[40. 50. 60.]

Mean of each row:
[20. 50. 80.]


In [36]:
marks = np.array([45,65,75,30,90])

results = np.where(marks >= 60,"pass","fail")
print(results)


['fail' 'pass' 'pass' 'fail' 'pass']


In [40]:
#SHORTING ARRAYS

In [41]:
marks = np.array([45,65,75,30,90])
print(np.sort(marks))
print(np.argsort(marks)) #marks ko thau haru herda


[30 45 65 75 90]
[3 0 1 2 4]


In [10]:
test = np.array([0,1,2,1,0,2,2,1,2,0])

values, count = np.unique(test, return_counts=True)

print("values:",values)
print("Count:",count) # kati chori return vako xa number vanera herna

values: [0 1 2]
Count: [3 3 4]


In [13]:
#FEATUREBMATRIX AND TARGET VECTOR

In [14]:
dataset = np.array([
    [2,30,60],
    [3,40,27],
    [6,38,38],
    [35,37,38],
    [66,27,49]
])
print(dataset)

[[ 2 30 60]
 [ 3 40 27]
 [ 6 38 38]
 [35 37 38]
 [66 27 49]]


In [17]:
x = dataset[:,0:2]
y = dataset[:, 2]
print("X",x)
print("\nY",y)

X [[ 2 30]
 [ 3 40]
 [ 6 38]
 [35 37]
 [66 27]]

Y [60 27 38 38 49]


In [18]:
A = np.array([
    [ 1,2,3],
    [ 4,5,6]
])
print("Transpose:\n",A.T)

Transpose:
 [[1 4]
 [2 5]
 [3 6]]


In [21]:
a = np.array([1,2,3])
b= np.array([4,5,6])
dotmatrix=np.dot(a,b)#dot le a ra b lai maltiply garera jodera average nikalxa
print(dotmatrix)

32


In [22]:
d = np.array([
  [2,60,50,45],
    [3,65,55,52],
    [4,70,60,65],
    [5,75,68,72],
    [6,80,74,78],
    [7,85,80,88],
    [8,90,86,92]
])
print("datatype:",d.dtype)
print("\nshape:",d.shape)
print("\ndimensin:",d.ndim)



datatype: int64

shape: (7, 4)

dimensin: 2


In [4]:
data = np.array([
    [1,2,3,],
    [4,5,6]
])
print("Flatten:")
print(data.flatten())
print("\nRavel:")
print(data.ravel())

Flatten:
[1 2 3 4 5 6]

Ravel:
[1 2 3 4 5 6]


In [11]:
A = np.array([
    [1,2,3],
    [4,5,6]
])
B = np.array([
    [7,8],
    [9,10],
    [11,12]
])
print(A@B)


[[ 58  64]
 [139 154]]


In [13]:
I = np.eye(3)
print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
